### PR TITLE
ci: setup travis ci

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Travis CI is a continuous integration system that integrates with GitHub and offers free CI for [Open Source projects](https://travis-ci.com/plans)

Other Apereo projects, including [uPortal](https://travis-ci.org/Jasig/uPortal) and [OpenEquella](https://travis-ci.org/equella/Equella), have found it to be an effective testing platform.

Here is a sample of what the output would look like for the notification hub ui https://travis-ci.com/ChristianMurphy/notification-ui/builds/92946317
It is running `mvn test -B` on Oracle JDK 8 and Open JDK 8 on Linux.

If this is something that would be a good fit for the notification hub ui, the instructions to enable Travis CI for a repo can be found here: https://docs.travis-ci.com/user/tutorial

### CODE REVIEW

**Comment by drewwills** [comment]
@hsun1 -- Are you in a position to enable Travis CI?  (See instructions in Christian's link)

**Comment by mairi** [comment]
@drewwills @ChristianMurphy I've followed the instructions to attempt enabling Travis CI - hopefully it has worked, but let me know if we need anything else.

**Comment by ChristianMurphy** [comment]
Its working well!
Thanks @mairi!
Could Travis CI also be enabled for the microservice? https://github.com/uoe-is-apps/notification-ms/pull/7

**Comment by drewwills** [comment]
Closing for now.

**Pull request closed without merging**
